### ISSUE TITLE
Is it possible to use Python?

### ISSUE THREAD

**Issue by LX-u** [fantasy-peak/cpp-freegpt-webui#12]
Can I use Python to deploy this project?

**Comment by fantasy-peak** [comment]
> Can I use Python to deploy this project?

You cannot deploy it using Python， you can use Docker to deploy it

**Comment by LX-u** [comment]
is this real GPT 4?

**Comment by fantasy-peak** [comment]
> is this real GPT 4?

I don't know if it's real gpt4, it depends on the provider, the service just calls the interface

**Comment by Joackk** [comment]
> > is this real GPT 4?
> 
> I don't know if it's real gpt4, it depends on the provider, the service just calls the interface

Is it possible to designate a service provider for api? How should I specify it?

**Comment by Joackk** [comment]
> > > > is this real GPT 4?
> > > 
> > > 
> > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > 
> > 
> > Is it possible to designate a service provider for api? How should I specify it?
> 
> ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> 
> Currently, This is a selection box， you can choose here

Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.

**Comment by fantasy-peak** [comment]
> > > > > is this real GPT 4?
> > > > 
> > > > 
> > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > 
> > > 
> > > Is it possible to designate a service provider for api? How should I specify it?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > Currently, This is a selection box， you can choose here
> 
> Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.

sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work

**Comment by Joackk** [comment]
> > > > > > is this real GPT 4?
> > > > > 
> > > > > 
> > > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > > 
> > > > 
> > > > Is it possible to designate a service provider for api? How should I specify it?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > > Currently, This is a selection box， you can choose here
> > 
> > 
> > Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.
> 
> sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work

Understood. Thank you for your answer.

**Comment by nqf** [comment]
> > > > > > > is this real GPT 4?
> > > > > > 
> > > > > > 
> > > > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > > > 
> > > > > 
> > > > > Is it possible to designate a service provider for api? How should I specify it?
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > > > Currently, This is a selection box， you can choose here
> > > 
> > > 
> > > Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.
> > 
> > 
> > sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work
> 
> Understood. Thank you for your answer.

 you can deploy this service（cpp-freegpt-webui） and access it through HTTP requests， Here is an example
```
☁  cpp-freegpt-webui [dev] ⚡  curl http://127.0.0.1:8858/backend-api/v2/conversation -d  '{"action":"_ask","conversation_id":"36bf7d48-088b-49c7-abb0-18a445b9d0a","jailbreak":"default","meta":{"content":{"content_type":"text","conversation":[],"internet_access":false,"parts":[{"content":"hello","role":"user"}]},"id":"7272942884126357994"},"model":"gpt-4-stream-liaobots"}' -v
* About to connect() to 127.0.0.1 port 8858 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8858 (#0)
> POST /backend-api/v2/conversation HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8858
> Accept: */*
> Content-Length: 283
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 283 out of 283 bytes
< HTTP/1.1 200 OK
< Server: CppFreeGpt
< Transfer-Encoding: chunked
< Content-Type: text/event-stream
< 
* Connection #0 to host 127.0.0.1 left intact
Hello! How can I assist you today?% 
```

**Comment by Joackk** [comment]
> > > > > > > > is this real GPT 4?
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > > > > 
> > > > > > 
> > > > > > Is it possible to designate a service provider for api? How should I specify it?
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > > > > Currently, This is a selection box， you can choose here
> > > > 
> > > > 
> > > > Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.
> > > 
> > > 
> > > sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work
> > 
> > 
> > Understood. Thank you for your answer.
> 
> you can deploy this service（cpp-freegpt-webui） and access it through HTTP requests， Here is an example
> 
> ```
> ☁  cpp-freegpt-webui [dev] ⚡  curl http://127.0.0.1:8858/backend-api/v2/conversation -d  '{"action":"_ask","conversation_id":"36bf7d48-088b-49c7-abb0-18a445b9d0a","jailbreak":"default","meta":{"content":{"content_type":"text","conversation":[],"internet_access":false,"parts":[{"content":"hello","role":"user"}]},"id":"7272942884126357994"},"model":"gpt-4-stream-liaobots"}' -v
> * About to connect() to 127.0.0.1 port 8858 (#0)
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 8858 (#0)
> > POST /backend-api/v2/conversation HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: 127.0.0.1:8858
> > Accept: */*
> > Content-Length: 283
> > Content-Type: application/x-www-form-urlencoded
> > 
> * upload completely sent off: 283 out of 283 bytes
> < HTTP/1.1 200 OK
> < Server: CppFreeGpt
> < Transfer-Encoding: chunked
> < Content-Type: text/event-stream
> < 
> * Connection #0 to host 127.0.0.1 left intact
> Hello! How can I assist you today?% 
> ```

Hi, well done. Can you call him in a third party program? How responsive is it?

**Comment by nqf** [comment]
I think you just need to start docker.and then send http request to http://127.0.0.1:8858/backend-api/v2/conversation

**Comment by fantasy-peak** [comment]
> > > > > > > is this real GPT 4?
> > > > > > 
> > > > > > 
> > > > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > > > 
> > > > > 
> > > > > Is it possible to designate a service provider for api? How should I specify it?
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > > > Currently, This is a selection box， you can choose here
> > > 
> > > 
> > > Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.
> > 
> > 
> > sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work
> 
> Hi, which uses docker to run the program in the example, is this what I use to start a third-party program so that a third party can use it? The last call oepn api is to fill in the official key?

docker run -p 8858:8858 -it --name freegpt fantasypeak/freegpt:latest

**Comment by Joackk** [comment]
> I think you just need to start docker.and then send http request to http://127.0.0.1:8858/backend-api/v2/conversation The above curl is an example

Hi, thank you for your reply. I will try him out

**Comment by Joackk** [comment]
> > > > > > > > is this real GPT 4?
> > > > > > > 
> > > > > > > 
> > > > > > > I don't know if it's real gpt4, it depends on the provider, the service just calls the interface
> > > > > > 
> > > > > > 
> > > > > > Is it possible to designate a service provider for api? How should I specify it?
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/29970876/264262626-83784ecd-305f-49a3-b43d-15785e6f63f6.png)
> > > > > Currently, This is a selection box， you can choose here
> > > > 
> > > > 
> > > > Can I use it to specify the service provider of api? Can you bring the api here to other software to use? I want to use it in translation software. I don't know why the original author's project reported an error.
> > > 
> > > 
> > > sorry you can't, i think you need to use native gpt4free provided API.But if the API doesn't work, you need to switch to another provider.gpt4free is actually just reversing the provider interface, and if the provider updates the interface, the API will not work
> > 
> > 
> > Hi, which uses docker to run the program in the example, is this what I use to start a third-party program so that a third party can use it? The last call oepn api is to fill in the official key?
> 
> docker run -p 8858:8858 -it --name freegpt fantasypeak/freegpt:latest

What I want to ask is, what is the difference between this command "Docker run - p 8858:8858- it -- name freegpt - e CHATPATH=/chat - e Providers=" [ "gpt 4 ChatgptAi ", "gpt 3.5 turbo stream DeepAi "] "fantasypeak/freegpt: last" and the feature you sent?

**Comment by Joackk** [comment]
> I think you just need to start docker.and then send http request to http://127.0.0.1:8858/backend-api/v2/conversation The above curl is an example

This is available, but you can't call it directly from the app, you'll get an error!

**Comment by nqf** [comment]
> > I think you just need to start docker.and then send http request to http://127.0.0.1:8858/backend-api/v2/conversation The above curl is an example
> 
> This is available, but you can't call it directly from the app, you'll get an error!

`curl http://127.0.0.1:8858/backend-api/v2/conversation -d  '{"action":"_ask","conversation_id":"36bf7d48-088b-49c7-abb0-18a445b9d0a","jailbreak":"default","meta":{"content":{"content_type":"text","conversation":[],"internet_access":false,"parts":[{"content":"hello","role":"user"}]},"id":"7272942884126357994"},"model":"gpt-4-stream-liaobots"}' -v`

**Comment by Joackk** [comment]
> > > 我认为你只需要启动docker.然后发送http请求到http://127.0.0.1:8858/backend-api/v2/conversation上面的curl是一个例子
> > 
> > 
> > 这是可用的，但您不能直接从应用程序调用它，您会收到错误！
> 
> `curl http://127.0.0.1:8858/backend-api/v2/conversation -d '{"action":"_ask","conversation_id":"36bf7d48-088b-49c7-abb0-18a445b9d0a","jailbreak":"default","meta":{"content":{"content_type":"text","conversation":[],"internet_access":false,"parts":[{"content":"hello","role":"user"}]},"id":"7272942884126357994"},"model":"gpt-4-stream-liaobots"}' -v`

Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?

**Comment by fantasy-peak** [comment]
> > > > 我认为你只需要启动docker.然后发送http请求到[http://127.0.0.1:8858/backend-api/v2/conversation上面的curl是一个例子](http://127.0.0.1:8858/backend-api/v2/conversation%E4%B8%8A%E9%9D%A2%E7%9A%84curl%E6%98%AF%E4%B8%80%E4%B8%AA%E4%BE%8B%E5%AD%90)
> > > 
> > > 
> > > 这是可用的，但您不能直接从应用程序调用它，您会收到错误！
> > 
> > 
> > `curl http://127.0.0.1:8858/backend-api/v2/conversation -d '{"action":"_ask","conversation_id":"36bf7d48-088b-49c7-abb0-18a445b9d0a","jailbreak":"default","meta":{"content":{"content_type":"text","conversation":[],"internet_access":false,"parts":[{"content":"hello","role":"user"}]},"id":"7272942884126357994"},"model":"gpt-4-stream-liaobots"}' -v`
> 
> Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?

I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?

**Comment by Joackk** [comment]
> > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> 
> I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?

I'm not sure if the program is written in python, isn't the api meant to be used by other programs?

**Comment by Joackk** [comment]
> > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> 
> I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?

I'm trying to use this api for an exe program, not a python script to call it, so I don't know how to call it from inside the exe, but the official and nova api's work fine!

**Comment by fantasy-peak** [comment]
> > > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> > 
> > 
> > I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?
> 
> I'm trying to use this api for an exe program, not a python script to call it, so I don't know how to call it from inside the exe, but the official and nova api's work fine!

what programming language？ c++?c#?

**Comment by fantasy-peak** [comment]
> > > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> > 
> > 
> > I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?
> 
> I'm not sure if the program is written in python, isn't the api meant to be used by other programs?

In fact, it is an http server. You can use any language to send http requests to the server. Curl is a simulation.

**Comment by Joackk** [comment]
> > > > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> > > 
> > > 
> > > I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?
> > 
> > 
> > I'm trying to use this api for an exe program, not a python script to call it, so I don't know how to call it from inside the exe, but the official and nova api's work fine!
> 
> what programming language？ c++?c#?

It seems like it is. I'm not sure

**Comment by Joackk** [comment]
> > > > Curl is available, but can you use him in some program that requires an api? I can't use it properly in other programs that need an api to use gpt. If you can, can you tell me how you did it?
> > > 
> > > 
> > > I don't quite understand what you mean, if your application is python, can't you use the requests library to send http requests?
> > 
> > 
> > I'm not sure if the program is written in python, isn't the api meant to be used by other programs?
> 
> In fact, it is an http server. You can use any language to send http requests to the server. Curl is a simulation.

Yes, but I am unable to use it properly. Can you use it in the application?

**Comment by nqf** [comment]
```
import requests
import json

# 定义要发送的JSON数据
data = {
     "action": "_ask",
     "conversation_id": "36bf7d48-088b-49c7-abb0-18a445b9d0a",
     "jailbreak": "default",
     "meta": {
          "content": {
               "content_type": "text",
               "conversation": [],
               "internet_access": False,
               "parts": [
                    {
                         "content": "hello",
                         "role": "user"
                    }
               ]
          },
          "id": "7272942884126357994"
     },
     "model": "gpt-3.5-turbo-stream-yqcloud"
}

# 将数据转换为JSON格式
json_data = json.dumps(data)

# 定义目标URL
url = "http://127.0.0.1:8858/backend-api/v2/conversation"  # 将此替换为您要发送请求的实际URL

# 定义请求头，通常需要设置"Content-Type"为"application/json"
headers = {"Content-Type": "application/json"}

# 发送POST请求，将JSON数据作为HTTP Body发送
response = requests.post(url, data=json_data, headers=headers)

# 检查响应状态码
if response.status_code == 200:
    print("请求成功")
    print("响应内容:", response.content.decode('UTF-8'))
else:
    print("请求失败")
    print("状态码:", response.status_code)

```
```
☁  cpp-freegpt-webui  ⚡  python test.py
请求成功
响应内容: 你好，有什么问题我可以帮助您吗？
```
