### ISSUE TITLE
Build error 'awaitable’ in namespace ‘boost::asio’ does not name a template type

### ISSUE THREAD

**Issue by bipindr123** [fantasy-peak/cpp-freegpt-webui#127]
Any idea?
Using GCC-13

`
error: In file included from src/free_gpt.cpp:20:
include/free_gpt.h:21:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:22:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:23:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:24:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:25:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:26:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:27:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:28:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:29:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:30:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:31:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:32:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:33:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:34:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:35:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:36:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:37:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:38:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:39:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:40:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:41:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:42:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/free_gpt.h:45:18: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/helper.hpp:12:75: error: ‘use_awaitable’ is not a member of ‘boost::asio’
include/helper.hpp:27:22: error: ‘jthread’ is not a member of ‘std’
include/helper.hpp:27:29: error: template argument 1 is invalid
include/helper.hpp:27:29: error: template argument 2 is invalid
include/helper.hpp:43:19: error: request for member ‘emplace_back’ in ‘((IoContextPool*)this)->IoContextPool::m_threads’, which is of non-class type ‘int’
include/helper.hpp:43:37: error: ‘jthread’ is not a member of ‘std’
include/helper.hpp:59:21: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
include/helper.hpp:69:19: error: lambda templates are only available with ‘-std=c++20’ or ‘-std=gnu++20’ [-Wc++20-extensions]
include/helper.hpp:111:36: error: ‘std::ranges’ has not been declared
include/helper.hpp:111:50: error: expected ‘>’ before ‘R’
include/helper.hpp:112:5: error: ‘requires’ does not name a type
include/helper.hpp:119:16: error: ‘std::ranges’ has not been declared
include/helper.hpp:119:30: error: expected ‘>’ before ‘Container’
include/helper.hpp:120:13: error: expected constructor, destructor, or type conversion before ‘(’ token
src/free_gpt.cpp:37:14: error: ‘std::ranges’ has not been declared
src/free_gpt.cpp:103:22: error: use of ‘auto’ in parameter declaration only available with ‘-std=c++20’ or ‘-fconcepts’
src/free_gpt.cpp:121:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:197:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:210:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:327:18: error: use of ‘auto’ in parameter declaration only available with ‘-std=c++20’ or ‘-fconcepts’
src/free_gpt.cpp:327:31: error: use of ‘auto’ in parameter declaration only available with ‘-std=c++20’ or ‘-fconcepts’
src/free_gpt.cpp:303:46: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v9::format’?
src/free_gpt.cpp:334:36: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v9::format’?
  334 |             auto error_info = std::format("[{}] -> [{}]", m_url, curl_easy_strerror(res));
src/free_gpt.cpp:340:25: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v9::format’?
src/free_gpt.cpp:381:6: error: ‘expected’ in namespace ‘std’ does not name a template type
src/free_gpt.cpp:424:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:545:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:619:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:677:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:838:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:954:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1004:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1099:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1176:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1338:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1419:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1544:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1594:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1673:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:1849:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2090:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2208:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2363:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2449:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2505:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2568:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2619:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type
src/free_gpt.cpp:2698:14: error: ‘awaitable’ in namespace ‘boost::asio’ does not name a template type`

**Comment by fantasy-peak** [comment]
This error is strange, it seems that the compiler is not gcc13, you can empty ~/.xmake directory and recompile?Do you have a low-level version of Boost installed on your system?

**Comment by fantasy-peak** [comment]
```
➜  ~ cd .xmake
➜  .xmake ls
cache  packages  profile  repositories
➜  .xmake rm -rf cache linux packages repositories
➜  .xmake cd
➜  ~ cd cpp-freegpt-webui/bin
➜  bin git:(dev) ✗ cd ..
➜  cpp-freegpt-webui git:(dev) ✗ rm -rf .xmake
➜  cpp-freegpt-webui git:(dev) ✗ xmake build -v -y``
```

**Comment by bipindr123** [comment]
thanks that fixed it. idk why xmake clean doesnt clean that folder smh

**Comment by fantasy-peak** [comment]
Maybe that directory is the cache directory of the library, so it will not be deleted, but sometimes there are strange compilation problems.
