### ISSUE TITLE
执行 xmake build -v -y报错

### ISSUE THREAD

**Issue by qiujianjuncom** [fantasy-peak/cpp-freegpt-webui#130]
![image](https://github.com/fantasy-peak/cpp-freegpt-webui/assets/31616308/7bc04535-bc09-44c8-880c-9449ffc6e656)

**Comment by fantasy-peak** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/blob/42aa0df64f7e8bc87a28e757c3b663a1c733dfbb/.github/workflows/ubuntu-clang18.yaml#L40  Please refer to this process. it need clang18,because it use c++23

**Comment by fantasy-peak** [comment]
https://github.com/openssl/openssl/issues/8996
