### ISSUE TITLE
Deployment on server

### ISSUE THREAD

**Issue by alinasir1596** [fantasy-peak/cpp-freegpt-webui#155]
I need to deploy the repo on my server for customer use and I have used xtekky g4f but after sometime the url starts to get rejected is it possible if I can deploy it and it doesn't runs into any issue like that?

**Comment by nqf** [comment]
You will definitely encounter rejection, in fact, the request was rejected by a third-party website

**Comment by alinasir1596** [comment]
So how can I overcome this issue is there any way to overcome this using any auto proxy or something?

**Comment by alinasir1596** [comment]
> You will definitely encounter rejection, in fact, the request was rejected by a third-party website
So how can I overcome this issue is there any way to overcome this using any auto proxy or something?

**Comment by fantasy-peak** [comment]
> > You will definitely encounter rejection, in fact, the request was rejected by a third-party website
> > So how can I overcome this issue is there any way to overcome this using any auto proxy or something?

You may want to wrap or modify gpt4free yourself, then decide that the call returns http code, then maintain a list of available providers, and automatically send the request to the next provider if it encounters a failure.

**Comment by fantasy-peak** [comment]
btw,Does gpt4free not automatically switch providers now?I haven't paid attention to the project for a while.

**Comment by alinasir1596** [comment]
> btw,Does gpt4free not automatically switch providers now?I haven't paid attention to the project for a while.
I didn't even checked with that recently.
