### ISSUE TITLE
Build fatal error: format: No such file or directory

### ISSUE THREAD

**Issue by bipindr123** [fantasy-peak/cpp-freegpt-webui#33]
Running xmake build -v gives the following error

[ 20%]: cache compiling.release src/free_gpt.cpp
/usr/bin/gcc -c -std=c++23 -Iinclude -isystem /home/ubuntu/.xmake/packages/o/openssl/1.1.1-t/45389129480645f6b5d519201fd29ab1/include -isystem /home/ubuntu/.xmake/packages/y/yaml_cpp_struct/v1.0.2/ba3f47c1dad64d64b1b0c182451288fd/include -isystem /home/ubuntu/.xmake/packages/m/magic_enum/v0.9.0/b7058fe3b4494be485a75baa4b3c2444/include -isystem /home/ubuntu/.xmake/packages/v/visit_struct/v1.1.0/70859d88e1594d11b2ed8a4be2fb1113/include -isystem /home/ubuntu/.xmake/packages/y/yaml-cpp/0.8.0/5cee0c2bc67a480fba56397b7957ccd9/include -isystem /home/ubuntu/.xmake/packages/s/spdlog/v1.12.0/b71e918ea13a4b7db6c1b6098388b0bb/include -isystem /home/ubuntu/.xmake/packages/b/boost/1.83.0/91ef36792a824e68b3b1d17c4cfb3202/include -isystem /home/ubuntu/.xmake/packages/b/bzip2/1.0.8/f3d161f5f92f487e939d378246898edf/include -isystem /home/ubuntu/.xmake/packages/i/inja/v3.4.0/66e6a5d79e9348768d27c879df5e8ba8/include -isystem /home/ubuntu/.xmake/packages/n/nlohmann_json/v3.11.2/39b878b8b2074cc4a5ccd1acb76aef3c/include -isystem /home/ubuntu/.xmake/packages/p/plusaes/v1.0.0/bd466a2cf43f4ef28e1fe7ae7aba47bf/include -isystem /home/ubuntu/.xmake/packages/z/zlib/v1.3/71dda3adb15a4c2597e114d96ae95578/include -O2 -Wall -Wextra -pedantic-errors -Wno-missing-field-initializers -Wno-ignored-qualifiers -o build/.objs/cpp-freegpt-webui/linux/arm64-v8a/release/src/free_gpt.cpp.o src/free_gpt.cpp
error: src/main.cpp:3:10: fatal error: format: No such file or directory
 "   3 | #include < format >"

**Comment by nqf** [comment]
need g++13

```
☁  lib  g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/gcc131/libexec/gcc/x86_64-redhat-linux/13/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure -v --enable-bootstrap --enable-languages=c,c++ --prefix=/usr/local/gcc131 --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=new --enable-plugin --enable-initfini-array --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.1.0 (GCC) 
```

**Comment by nqf** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/actions/runs/6093740462/job/16533925164 

![image](https://github.com/fantasy-peak/cpp-freegpt-webui/assets/29970876/429749e8-e273-4e38-900f-0507808ad039)

**Comment by bipindr123** [comment]
@nqf thanks, after updating to gcc-13 I still have this build error, I'm guessing it has something to do with dependencies also being some higher version?

arm64-v8a/release/src/free_gpt.cpp.o src/free_gpt.cpp
error: src/free_gpt.cpp:11:10: fatal error: curl/curl.h: No such file or directory
   11 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

**Comment by fantasy-peak** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/blob/4405fd1bb68daf9a9b9b3781d0c2142a09d5e451/.github/workflows/ubuntu-gcc13.yaml#L21 need install curl-dev

**Comment by fantasy-peak** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/blob/4405fd1bb68daf9a9b9b3781d0c2142a09d5e451/.github/workflows/ubuntu-gcc13.yaml#L22  also need this

**Comment by fantasy-peak** [comment]
Because a provider(you) needs this library(libcurl-impersoate)

**Comment by bipindr123** [comment]
@fantasy-peak @nqf Perfect! That fixed it. I was assuming xmake would handle the dependencies but it looks like its using libs that are not found in stable ubuntu 22. Thank you soo much for your help.
