### ISSUE TITLE
error: src/main.cpp:3:10: fatal error: format: No such file or directory

### ISSUE THREAD

**Issue by yukuai90** [fantasy-peak/cpp-freegpt-webui#40]
error: src/main.cpp:3:10: fatal error: format: No such file or directory
    3 | #include <format>

**Comment by nqf** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/issues/33

**Comment by fantasy-peak** [comment]
Please read the issue above, it should be able to solve your problem.
