### ISSUE TITLE
最新的提问无法关联历史提问

### ISSUE THREAD

**Issue by WrBug** [fantasy-peak/cpp-freegpt-webui#45]
![image](https://github.com/fantasy-peak/cpp-freegpt-webui/assets/12111403/e13a3c45-e21d-430a-aa5b-1e799c042891)
如图，第二个问题【还有其他方式吗】，理论上也是跟排序相关的回答

**Comment by fantasy-peak** [comment]
没有实现连续提问，如果连续提问需要把历史传递过去。目前没有传递。只能单个问答

**Comment by WrBug** [comment]
> 只

后续有支持的计划吗

**Comment by fantasy-peak** [comment]
https://github.com/xtekky/gpt4free/issues/721

**Comment by fantasy-peak** [comment]
> > 只
> 
> 后续有支持的计划吗

我想增加这个功能，但是目前暂时没精力，毕竟这个只是业余时间在做

**Comment by fantasy-peak** [comment]
目前只有两个供应商支持，其中openapi需要key
