### ISSUE TITLE
CHAT_PATH not working for static files

### ISSUE THREAD

**Issue by Balshgit** [fantasy-peak/cpp-freegpt-webui#59]
Client static files like `style.css` can be accessible only via root url

CHAT_PATH do nothing for them

**Comment by fantasy-peak** [comment]
CHAT_PATH just needs to be checked when logging in，https://github.com/fantasy-peak/cpp-freegpt-webui/blob/main/src/main.cpp#L134 ，Do you want all static files to be obtained from this path? btw The static resource acquisition path is specially processed https://github.com/fantasy-peak/cpp-freegpt-webui/blob/main/src/main.cpp#L145

**Comment by fantasy-peak** [comment]
> Client static files like `style.css` can be accessible only via root url
> 
> CHAT_PATH do nothing for them

done

**Comment by Balshgit** [comment]
thx
