### ISSUE TITLE
The assistant suffers from amnesia

### ISSUE THREAD

**Issue by Olejja** [fantasy-peak/cpp-freegpt-webui#62]
You ask the assistant a question, he answers something, you ask a clarifying question, but he doesn’t understand where he is, what he is, who he is and what’s going on.

**Comment by fantasy-peak** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui/issues/45   You mean you want to talk to the robot continuously, right?  There are many providers that do not support continuous chat

**Comment by Olejja** [comment]
I want him to carry on the conversation for a while. At this moment he does not understand what is happening already in the second message. This really hurts!

**Comment by fantasy-peak** [comment]
> I want him to carry on the conversation for a while. At this moment he does not understand what is happening already in the second message. This really hurts!

you can try aivvm provider

**Comment by Olejja** [comment]
It's always unavailable to me

```
return unexpected http status code: 403(Forbidden)
```

**Comment by fantasy-peak** [comment]
Did you pull the latest docker image？, it was recently updated

**Comment by fantasy-peak** [comment]
![Uploading IMG_20230927_204133.jpg…]()

**Comment by fantasy-peak** [comment]
![IMG_20230927_204133](https://github.com/fantasy-peak/cpp-freegpt-webui/assets/82742316/58d95086-9b76-4f0b-8dbf-28f0fd338577)

**Comment by Olejja** [comment]
I downloaded a new docker image, nothing changed.

**Comment by fantasy-peak** [comment]
Maybe your ip is risk-controlled，I can access，The above screenshot is the result of my access

**Comment by fantasy-peak** [comment]
> I downloaded a new docker image, nothing changed.

add two provider support continuous chat

**Comment by Olejja** [comment]
Everything is fine now. Thank

**Comment by fantasy-peak** [comment]
> Everything is fine now. Thank

Please help to add a ⭐ if possible
