### ISSUE TITLE
Error after docker run

### ISSUE THREAD

**Issue by yswlww** [fantasy-peak/cpp-freegpt-webui#64]
[2023-09-28 10:06:00.164][thread 31][startSession][main.cpp:122][info] assets_path: [/chat/assets]
[2023-09-28 10:06:00.166][thread 31][startSession][main.cpp:134][info] async_read: bad method

Please help

**Comment by fantasy-peak** [comment]
if you use httpclient send request.this is a example  https://github.com/fantasy-peak/cpp-freegpt-webui/issues/12

**Comment by fantasy-peak** [comment]
> [2023-09-28 10:06:00.164][thread 31][startSession][main.cpp:122][info] assets_path: [/chat/assets] [2023-09-28 10:06:00.166][thread 31][startSession][main.cpp:134][info] async_read: bad method
> 
> Please help

Do you use a domain name to access? if so You can try using ip

**Comment by yswlww** [comment]
thanks got it i forget the path /chat
