### ISSUE TITLE
How to run in Huggingface?

### ISSUE THREAD

**Issue by achyuth4** [fantasy-peak/cpp-freegpt-webui#68]
Huggingface.co is website which provides free cloud server of 16gb Ram to work on any AI projects. You can pay and get more resources to run.

But, can I run this program on HuggingFace.

Please reply!

**Comment by fantasy-peak** [comment]
I haven't used it(hugginface.io ' free cloud server), it docker cloud server can it just pull the image from docker hub and run it?

**Comment by fantasy-peak** [comment]
https://huggingface.co/docs/hub/spaces-run-with-docker this? I'm not sure. You might need to try.

**Comment by achyuth4** [comment]
ok brother! I'll try
