### ISSUE TITLE
Is there a docker version supporting arm64?

### ISSUE THREAD

**Issue by koelan** [fantasy-peak/cpp-freegpt-webui#70]
Thank you for creating this project. Can I ask for a docker version that supports arm64?

**Comment by fantasy-peak** [comment]
Currently there is no arm version docker image，I'll try to make an ARM version image, but I can't give a specific time.Currently I don't know how to make ARM version image，By the way, if you approve of this project, please give a ⭐，Your support is the driving force behind my progress.

**Comment by fantasy-peak** [comment]
It seems that you can use this software(QEMU) to run x86docker image at this time

**Comment by fantasy-peak** [comment]
> Thank you for creating this project. Can I ask for a docker version that supports arm64?

https://ivonblog.com/posts/run-x86-docker-image-on-arm-platform/

**Comment by koelan** [comment]
> > Thank you for creating this project. Can I ask for a docker version that supports arm64?
> 
> https://ivonblog.com/posts/run-x86-docker-image-on-arm-platform/

Thank you for your quick reply and solution! Will try it out! ⭐⭐⭐

**Comment by koelan** [comment]
Work well after add the following: 
`sudo docker run --rm --privileged aptman/qus -s -- -p x86_64`

Thanks again!
