### ISSUE TITLE
403(Forbidden)

### ISSUE THREAD

**Issue by Olejja** [fantasy-peak/cpp-freegpt-webui#71]
Several providers have recently been added for continuous chat. But they are very unstable... The last few days I have been getting this error more and more often, which makes my ass burn with a bright flame 😞:

``
return unexpected http status code: 403(Forbidden)`
``

**Comment by fantasy-peak** [comment]
Please use other available provider because I am on vacation recently and I have not been able to update it yet

**Comment by Olejja** [comment]
```
gpt-3.5-turbo-16k-stream-Ylokh
gpt-3.5-turbo-stream-aivvm
```

**Comment by fantasy-peak** [comment]
> ```
> gpt-3.5-turbo-16k-stream-Ylokh
> gpt-3.5-turbo-stream-aivvm
> ```

Do you use the latest docker image, the two providers can work

**Comment by Olejja** [comment]
Yes, this is the latest version

**Comment by fantasy-peak** [comment]
> Yes, this is the latest version

Aren't you visiting too frequently?，I just went and asked a few questions in a row and there was no 403 error.

**Comment by Olejja** [comment]
No, I just correspond with the chatbot in the same browser tab. It understands me far from the first time, so I explain where it got it wrong, then it gets it wrong again, I point out the error in the task over and over, then I get a 403(Forbidden). I've tried restarting docker container and refreshing the browser tab, but because of the error I can't continue chatting or create a new chat and start over.

**Comment by fantasy-peak** [comment]
> No, I just correspond with the chatbot in the same browser tab. It understands me far from the first time, so I explain where it got it wrong, then it gets it wrong again, I point out the error in the task over and over, then I get a 403(Forbidden). I've tried restarting docker container and refreshing the browser tab, but because of the error I can't continue chatting or create a new chat and start over.

In fact, 403 is not returned by docker service, so it is useless for you to restart docker, 403 is returned by the provider，There's nothing I can do about it because I can't change the provider.

**Comment by Olejja** [comment]
Thank you for trying to help.
